augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
    maxpool_last2: true
  name: resnet12
batch_size: 64
classifier:
  kwargs:
    feat_dim: 640
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 200
  name: AFR
data_root: ../../autodl-tmp/miniImageNet--ravi/miniImageNet--ravi/
deterministic: true
n_gpu: 1
device_ids: 0
episode_size: 1
epoch: 170
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
# to be changed
lr_scheduler:
  kwargs:
    gamma: 0.1
    milestones:
    - 100
    - 150
  name: MultiStepLR

optimizer:
  kwargs:
    lr: 0.05
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
parallel_part:
- emb_func
- classifier
# port: 48828
pretrain_path: ./pre_train_resnet/best_model.pth #预训练模型, 针对的是resnet12
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
- classifier
seed: 1
tag: null
tb_scale: 3.3333333333333335
val_per_epoch: 1      # NOTE: save best model
# val_per_epoch: 20   # NOTE: just save last model
test_episode: 60   # test/val n_episodes, number of episodes in meta val
test_epoch: 5
test_query: 15
test_shot: 1
test_way: 5
train_episode: 10
query_num: 15
shot_num: 1
use_memory: false
way_num: 5
workers: 8